# Sendgrid
development:
  SENDGRID_ADDRESS: localhost
  SENDGRID_DOMAIN: mail.google.com
  SENDGRID_PORT: '1025'
  SENDGRID_API_KEY:
  SENDGRID_USERNAME:
  SENDGRID_PASSWORD:
test:
  SENDGRID_ADDRESS: localhost
  SENDGRID_DOMAIN: mail.google.com
  SENDGRID_PORT: '1025'
  SENDGRID_API_KEY:
  SENDGRID_USERNAME:
  SENDGRID_PASSWORD:
production:
  SENDGRID_ADDRESS: smtp.sendgrid.net
  SENDGRID_DOMAIN: mail.google.com
  SENDGRID_PORT: '587'
  SENDGRID_API_KEY: production_key
  SENDGRID_USERNAME: production_username
  SENDGRID_PASSWORD: production_password

